# Generated by Django 3.2.19 on 2023-08-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.TextField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('partner_name', models.CharField(max_length=250)),
                ('sdg', models.IntegerField()),
            ],
        ),
    ]
