# Generated by Django 3.2.19 on 2023-08-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdgs', '0003_alter_point_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='sdg',
        ),
        migrations.AddField(
            model_name='point',
            name='sdgs',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
